### ISSUE TITLE
Support for NewTek TriCaster video switchers

### ISSUE THREAD

**Issue by jstarpl** [nrkno/sofie-timeline-state-resolver#192]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

* **Summary**

NewTek TriCaster-series vision mixers use a [well documented](http://a6ce85f34b101e4ba428-38e91d4533ffbe5c8042650a77a3ed34.r56.cf1.rackcdn.com/TriCaster/AI%20Guide/Automation%20and%20Integration%20Guide.pdf) XML-based control protocol for integration with automation systems. The switchers support legacy bare TCP/IP connections, but they also support WebSockets as a transport mechanism. The protocol allows a wide range of control from the outside. To be useful for controlling the switchers from Sofie, the module should support changing cross-points, controlling the keyer status & M/E control (auto takes, cuts, transition change).

Ideally, it should also support DDR control for playback (clip import into bin, selection for playback, playback control), Title Template control (updating template values), Virtual Sets control (change preset, speed, animate on/off) and triggering Macros.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

NewTek TriCaster integration guide: http://a6ce85f34b101e4ba428-38e91d4533ffbe5c8042650a77a3ed34.r56.cf1.rackcdn.com/TriCaster/AI%20Guide/Automation%20and%20Integration%20Guide.pdf
A detailed list of available commands: https://jonjones.co/blog/newtek-tricaster-network-control-advanced-edition/
Bitfocus Companion module for TriCasters: https://github.com/bitfocus/companion-module-newtek-tricaster

**Comment by ianshade** [comment]
Just in case somebody was considering picking this up, I should mention that work on this feature is already in progress.

**Comment by jstarpl** [comment]
This has been already by TV2 Danmark. Thank you!
