### ISSUE TITLE
Upgrade obs-websocket-js to v5

### ISSUE THREAD

**Issue by from-the-river-to-the-sea** [nrkno/sofie-timeline-state-resolver#214]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
obs-websocket has undergone [major changes](https://github.com/obsproject/obs-websocket/releases). Currently, TSR uses v4 of the protocol. [v5 of the protocol](https://github.com/obs-websocket-community-projects/obs-websocket-js/releases/tag/v5.0.0) is already available for OBS 27, the current release of OBS. OBS 28 is coming out in the next couple of weeks, and will now ship with obs-websocket v5, as opposed to v4 which required manual installation by the user. Of note is that upgrading obs-websocket-js to v5 or above will completely remove compatibility for v4 of the protocol. This will therefore be a breaking change. The upgrade itself should be pretty easy thanks to the good typedefs present in `obs-websocket-js`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
My primary motivation for wanting to upgrade `obs-websocket-js` in TSR is so that [SuperConductor](https://github.com/SuperFlyTV/SuperConductor) can use it.

**Comment by jstarpl** [comment]
Yep, we should do that. I don't expect a lot of people needing to use v4 of the protocol.

**Comment by Julusian** [comment]
I'm not sure if it will be any use to anyone, but I wanted to try some stuff with v5 in TSR so I hacked in enough support to achieve what I wanted to test https://github.com/nrkno/sofie-timeline-state-resolver/commit/ee1ab75b9d799f72745e93396c4b369e0c1a7799

**Comment by Julusian** [comment]
Fixed by #316
