### ISSUE TITLE
Support headers in HTTP Send

### ISSUE THREAD

**Issue by alvancamp** [nrkno/sofie-timeline-state-resolver#216]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Some HTTP requests, particularly ones that require authentication, often use HTTP headers. It would be great to have these supported in TSR.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
The particular use case I'm thinking of is running ads on Twitch, but there are many other use cases.

**Comment by PeterC89** [comment]
Implemented in #255
